console.log('hello')
const config = {
    sliders: [
        {
            label: 'particleCount',
            min: 1,
            max: 10000,
            value: 1000,
            step: 1,
        },
        {
            label: 'flowForce',
            min: 0.001,
            max: 2,
            value: 1,
            step: 0.001,
        },
        {
            label: 'cols',
            min: 1,
            max: 100,
            value: 20,
            step: 1,
        },
        {
            label: 'rows',
            min: 1,
            max: 100,
            value: 20,
            step: 1,
        },
        {
            label: 'xNoiseStep',
            min: 0.001,
            max: 3,
            value: .01,
            step: 0.001,
        },
        {
            label: 'yNoiseStep',
            min: 0.001,
            max: 3,
            value: .01,
            step: 0.001,
        },
        {
            label: 'zNoiseStep',
            min: 0.0001,
            max: 1,
            value: .003,
            step: 0.0001,
        },
        {
            label: 'maxAngle',
            min: 0,
            max: Math.PI * 2 * 4,
            value: Math.PI * 2 * 4,
            step: 0.1,
        },
        {
            label: 'maxSpeed',
            min: 0.1,
            max: 4,
            value: 2,
            step: 0.1,
        },
        {
            label: 'hue',
            min: 0,
            max: 360,
            value: 3,
            step: 1,
        },
        {
            label: 'saturation',
            min: 0,
            max: 100,
            value: 100,
            step: 1,
        },
        {
            label: 'brightness',
            min: 0,
            max: 100,
            value: 100,
            step: 1,
        },
        {
            label: 'alpha',
            min: 0.01,
            max: 1,
            value: .03,
            step: 0.01,
        },
        {
            label: 'frame',
            min: 0,
            max: 10000,
            value: 40,
            step: 1,
        },
    ],
}
